service:
  name: products-api
package:
  individually: true
  exclude:
    - "**/**"
plugins:
  - serverless-aws-documentation
  - serverless-offline
custom:
  documentation:
    api:
      info:
        version: 1.0.0
        title: ${self:service.name}
        description: API to manage products in ElasticSearch
provider:
  name: aws
  runtime: nodejs12.x
  stackName: ${self:service.name}-stack
  apiName: ${self:service.name}
  stage: ${opt:stage, 'prod'}
  region: eu-central-1
  deploymentBucket:
    name: kaskadi-serverless-deployment-bucket
  stackTags:
    app: kaskadi
  tags:
    app: kaskadi
    service: ${self:service.name}
    logical-unit: products
    type: http
  environment:
    ES_ID: ${env:ES_ID}
    ES_SECRET: ${env:ES_SECRET}
    ES_ENDPOINT: ${env:ES_ENDPOINT}
functions:
  DeleteProduct: ${file(./lambdas/delete-product/serverless.yml)}
  GetProduct: ${file(./lambdas/get-product/serverless.yml)}
  SearchProducts: ${file(./lambdas/search-products/serverless.yml)}
layers:
  ApiLayer: ${file(./layer/serverless.yml)}
resources:
  Resources:
    CognitoAuthorizer: ${file(./resources/cognito-authorizer/serverless.yml)}
