handler: lambdas/get-product/get-product.handler
name: get-product
layers:
  - { Ref: ApiLayerLambdaLayer }
package:
  include:
    - lambdas/get-product/get-product.js
    - lambdas/get-product/helpers/**
events:
  - http:
      method: get
      path: '{id}'
      cors: true
      authorizer:
        type: COGNITO_USER_POOLS
        authorizerId: !Ref CognitoAuthorizer
      kaskadi-docs:
        description: This endpoint allows client to retrieve data of a specific product via its ID.
