handler: lambdas/get-product/get-product.handler
name: get-product
layers:
  - { Ref: ApiLayerLambdaLayer }
package:
  include:
    - lambdas/get-product/get-product.js
    - lambdas/get-product/helpers/**
events:
  - http:
      method: get
      path: '{id}'
      cors: true
      authorizer:
        type: COGNITO_USER_POOLS
        authorizerId: !Ref CognitoAuthorizer
      kaskadi-docs:
        description: This endpoint allows client to retrieve data of a specific product via its ID.
        examples:
          - request:
              pathParameters:
                id: valid_id
            response:
              statusCode: 200
              headers:
                'Access-Control-Allow-Origin': '*'
              body:
                product-data-1: some product data
                product-data-2: another product data field
                product-data-N: the last field of data for this product
          - request:
              pathParameters:
                id: non_existant_id
            response:
              statusCode: 404
              headers:
                'Access-Control-Allow-Origin': '*'
              body:
                message: Product not found...
