handler: lambdas/products-root-handler/products-root-handler.handler
name: products-root-handler
layers:
  - { Ref: ApiLayerLambdaLayer }
package:
  include:
    - lambdas/products-root-handler/products-root-handler.js
events:
  - http:
      method: get
      path: /
      cors: true
      authorizer:
        type: COGNITO_USER_POOLS
        authorizerId: !Ref CognitoAuthorizer
      kaskadi-docs:
        description: This endpoint is a fallback for when client forgets to provide an ID for product data retrieval.
        examples:
          - request: {}
            response:
              statusCode: 400
              headers:
                'Access-Control-Allow-Origin': '*'
              body:
                message: Path parameter for product ID missing... (/products/{id})
  - http:
      method: post
      path: /
      cors: true
      authorizer:
        type: COGNITO_USER_POOLS
        authorizerId: !Ref CognitoAuthorizer
      kaskadi-docs:
        description: This endpoint is a fallback for when client forgets to provide an ID for product data update.
        examples:
          - request: {}
            response:
              statusCode: 400
              headers:
                'Access-Control-Allow-Origin': '*'
              body:
                message: Path parameter for product ID missing... (/products/{id})
  - http:
      method: delete
      path: /
      cors: true
      authorizer:
        type: COGNITO_USER_POOLS
        authorizerId: !Ref CognitoAuthorizer
      kaskadi-docs:
        description: This endpoint is a fallback for when client forgets to provide an ID for product deletion.
        examples:
          - request: {}
            response:
              statusCode: 400
              headers:
                'Access-Control-Allow-Origin': '*'
              body:
                message: Path parameter for product ID missing... (/products/{id})