handler: lambdas/save-product/save-product.handler
name: save-product
layers:
  - { Ref: ApiLayerLambdaLayer }
package:
  include:
    - lambdas/save-product/save-product.js
    - lambdas/save-product/helpers/**
events:
  - http:
      method: post
      path: '{id}'
      cors: true
      authorizer:
        type: COGNITO_USER_POOLS
        authorizerId: !Ref CognitoAuthorizer
      kaskadi-docs:
        description: This endpoint allows client to update data of a specific product via its ID. The request body should contain the new product data.
        body:
          - key: example-field-1
            description: A data field to write in the database for the given product
          - key: example-field-N
            description: A data field to write in the database for the given product
        examples:
          - request:
              pathParameters:
                id: product_id
              body:
                product-data-1: some product data
                product-data-2: another product data field
                product-data-N: the last field of data for this product
            response:
              statusCode: 200
              headers:
                'Access-Control-Allow-Origin': '*'
              body:
                message: Product with ID product_id successfully saved!
          - request:
              pathParameters:
                id: product_id
            response:
              statusCode: 400
              headers:
                'Access-Control-Allow-Origin': '*'
              body:
                message: 'Request body missing: no product data to save...'
