handler: lambdas/save-product/save-product.handler
name: save-product
layers:
  - { Ref: ApiLayerLambdaLayer }
package:
  include:
    - lambdas/save-product/save-product.js
    - lambdas/save-product/helpers/**
events:
  - http:
      method: post
      path: '{id}'
      cors: true
      authorizer:
        type: COGNITO_USER_POOLS
        authorizerId: !Ref CognitoAuthorizer
      kaskadi-docs:
        description: This endpoint allows client to update data of a specific product via its ID. The request body should contain the new product data.
        body:
          - key: example-field-1
            description: A data field to write in the database for the given product
          - key: example-field-N
            description: A data field to write in the database for the given product
